import { Manga, MangaVolume, IMangaVolume, MangaSummary } from './types'

// 全漫画データ
export const mangaData: Record<string, Manga> = {
  "hunter-x-hunter": {
    id: 1,
    title: "ハンター×ハンター",
    slug: "hunter-x-hunter",
    image: "/images/hunter-x-hunter/volume-1.jpg",
    description: "父親を探すため、そして憧れのハンターになるため、少年ゴンの冒険が始まる。念能力を駆使したバトルと緻密に練られたストーリーが魅力の冒険ファンタジーで、様々な試験や任務に挑戦していく。キルア、クラピカ、レオリオといった仲間たちとの出会い、そして幻影旅団やキメラアントなど、強力な敵との戦いを通じて、ゴンは成長していく。念能力の奥深さ、人間の心理描写、そして壮大な世界観が織りなす、深みのある物語である。",
    author: "冨樫義博",
    authorSlug: "togashi-yoshihiro",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "1998-",
    status: "休載中",
    volumeCount: 37,
    rating: 4.9,
    genres: ["少年", "アクション", "冒険", "ファンタジー"],
    volumes: [
      {
        number: 1,
        image: "/images/hunter-x-hunter/volume-1.jpg",
        title: "HUNTER×HUNTER",
        releaseDate: "1998-06-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088727533",
      },
      {
        number: 2,
        image: "/images/hunter-x-hunter/volume-2.jpg",
        title: "出会い",
        releaseDate: "1998-09-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088727533",
      },
      {
        number: 3,
        image: "/images/hunter-x-hunter/volume-3.jpg",
        title: "決着",
        releaseDate: "1998-12-03",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088727533",
      },
      ...Array.from({ length: 34 }, (_, i) => ({
        number: i + 4,
        image: `/images/hunter-x-hunter/volume-${i + 4}.jpg`,
        title: "ハンター×ハンター",
        releaseDate: `1999-${((i + 4) % 12) + 1}-01`,
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088727533",
      })),
    ],
  },
  "yu-yu-hakusho": {
    id: 23,
    title: "幽☆遊☆白書",
    titleRomaji: "Yu Yu Hakusho",
    slug: "yu-yu-hakusho",
    image: "/images/yu-yu-hakusho/volume-1.jpg",
    description: "不良少年・浦飯幽助は、交通事故で命を落とすが、予想外の展開で霊界特防隊として復活。霊界の使者として、人間界と霊界のバランスを保つために戦う。妖怪との戦い、暗黒武術会での激闘、そして魔界との戦いを通じて、幽助と仲間たちは成長していく。友情と絆、そして正義を貫く心を描いた、アクションとファンタジーの要素を兼ね備えた名作。",
    author: "冨樫義博",
    authorSlug: "togashi-yoshihiro",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "1990-1994",
    status: "完結",
    volumeCount: 19,
    rating: 4.8,
    genres: ["少年", "アクション", "ファンタジー", "バトル"],
    volumes: [
      {
        number: 1,
        image: "/images/yu-yu-hakusho/volume-1.jpg",
        title: "幽☆遊☆白書",
        releaseDate: "1990-12-10",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088712737",
        description: "不良少年・浦飯幽助は、交通事故で命を落とすが、予想外の展開で霊界特防隊として復活。霊界の使者として、人間界と霊界のバランスを保つために戦う。"
      },
      ...Array.from({ length: 18 }, (_, i) => ({
        number: i + 2,
        image: `/images/yu-yu-hakusho/volume-${i + 2}.jpg`,
        title: "幽☆遊☆白書",
        releaseDate: `1991-${((i + 2) % 12) + 1}-01`,
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088712737",
      })),
    ],
  },
  "level-e": {
    id: 24,
    title: "レベルE",
    titleRomaji: "Level E",
    slug: "level-e",
    image: "/images/level-e/volume-1.jpg",
    description: "宇宙人の王子・ドグラが地球にやってきて、高校生の筒井雪隆の家に居候することに。ドグラは天才的な頭脳の持ち主だが、性格は極めて悪質で、周囲を巻き込んで様々な騒動を引き起こす。SFとコメディが融合した独特の世界観で、宇宙人たちの珍騒動を描く。冨樫義博の作風の幅広さを示す、異色の傑作。",
    author: "冨樫義博",
    authorSlug: "togashi-yoshihiro",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "1995-1997",
    status: "完結",
    volumeCount: 3,
    rating: 4.7,
    genres: ["少年", "SF", "コメディ", "ファンタジー"],
    volumes: [
      {
        number: 1,
        image: "/images/level-e/volume-1.jpg",
        title: "レベルE",
        releaseDate: "1996-03-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088720896",
        description: "宇宙人の王子・ドグラが地球にやってきて、高校生の筒井雪隆の家に居候することに。ドグラは天才的な頭脳の持ち主だが、性格は極めて悪質で、周囲を巻き込んで様々な騒動を引き起こす。"
      },
      {
        number: 2,
        image: "/images/level-e/volume-2.jpg",
        title: "レベルE",
        releaseDate: "1996-09-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/408872090X",
      },
      {
        number: 3,
        image: "/images/level-e/volume-3.jpg",
        title: "レベルE",
        releaseDate: "1997-03-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088720918",
      },
    ],
  },
  "jujutsu-kaisen": {
    id: 2,
    title: "呪術廻戦",
    titleRomaji: "Jujutsu Kaisen",
    slug: "jujutsu-kaisen",
    image: "/images/jujutsu-kaisen/volume-4.jpg",
    description: "高校生の虎杖悠仁は、特級呪物「両面宿儺の指」を体内に取り込んでしまい、呪術師の世界に足を踏み入れることになる。呪いの力を持つ呪術師として成長していく物語。",
    author: "芥見下々",
    authorSlug: "akutami-gege",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2018-",
    status: "連載中",
    volumeCount: 28,
    rating: 4.8,
    genres: ["少年", "アクション", "ファンタジー", "ホラー"],
    volumes: [
      {
        number: 1,
        image: "/images/jujutsu-kaisen/volume-1.png",
        title: "両面宿儺",
        releaseDate: "2018-07-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088815169",
        description: "高校生の虎杖悠仁は、特級呪物「両面宿儺の指」を体内に取り込んでしまう。呪術師の世界に足を踏み入れた彼の運命は大きく変わることになる。"
      },
      {
        number: 2,
        image: "/placeholder.svg?height=150&width=100",
        title: "呪術高専",
        releaseDate: "2018-09-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088816122",
        description: "呪術高専に入学した虎杖。五条悟の指導のもと、伏黒や釘崎と共に呪術師としての修行を始める。"
      },
      {
        number: 3,
        image: "/placeholder.svg?height=150&width=100",
        title: "幼魚と逆罰",
        releaseDate: "2018-11-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088816696",
        description: "呪術高専の一年生たちは、実戦任務に参加することに。しかし、そこには予想外の強敵が待ち受けていた。"
      },
      {
        number: 4,
        image: "/images/jujutsu-kaisen/volume-4.jpg",
        title: "京都姉妹校交流会",
        releaseDate: "2019-01-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088817277",
        description: "京都の呪術高専との交流会が始まる。しかし、その裏では大きな陰謀が進行していた。"
      },
      {
        number: 28,
        image: "/images/jujutsu-kaisen/volume-28.jpg",
        title: "呪術廻戦",
        releaseDate: "2024-11-01",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088836421",
      },
    ],
  },
  "kimetsu-no-yaiba": {
    id: 2,
    title: "鬼滅の刃",
    titleRomaji: "Kimetsu no Yaiba",
    slug: "kimetsu-no-yaiba",
    image: "/images/kimetsu-no-yaiba/volume-7.jpg",
    description: "時は大正。竈門炭治郎は、家族を鬼に惨殺され、唯一生き残った妹の禰豆子が鬼と化してしまったことを知る。妹を人間に戻すため、そして家族を殺した鬼を討つため、炭治郎は「鬼殺隊」の道を歩むことになる。",
    author: "吾峠呼世晴",
    authorSlug: "gotouge-koyoharu",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2016-2020",
    status: "完結",
    volumeCount: 23,
    rating: 4.9,
    genres: ["少年", "アクション", "ファンタジー", "歴史"],
    volumes: [
      {
        number: 1,
        image: "/images/kimetsu-no-yaiba/volume-1.jpg",
        title: "残酷",
        releaseDate: "2016-06-03",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088807239",
        description: "家族を鬼に殺された炭治郎は、唯一生き残った妹の禰豆子が鬼になってしまったことを知る。妹を人間に戻すため、鬼殺隊の道を歩むことを決意する。"
      },
      {
        number: 2,
        image: "/images/kimetsu-no-yaiba/volume-2.jpg",
        title: "お前の鼓動を聞け",
        releaseDate: "2016-08-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088807956",
        description: "炭治郎は水の呼吸を習得し、初めての任務に赴く。そこで出会ったのは、人を喰らう鬼だった。"
      },
      {
        number: 3,
        image: "/images/kimetsu-no-yaiba/volume-3.jpg",
        title: "お前の鼓動を聞け",
        releaseDate: "2016-10-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/408880826X",
        description: "炭治郎は鬼殺隊の最終選別に参加する。そこで待ち受けていたのは、命をかけた試練だった。"
      },
      {
        number: 4,
        image: "/images/kimetsu-no-yaiba/volume-4.jpg",
        title: "お前の鼓動を聞け",
        releaseDate: "2016-12-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088808820",
        description: "炭治郎は初めての任務で、人を喰らう鬼と対峙する。その中で、鬼の過去を知ることになる。"
      },
      {
        number: 5,
        image: "/images/kimetsu-no-yaiba/volume-5.jpg",
        title: "お前の鼓動を聞け",
        releaseDate: "2017-02-03",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088810264",
        description: "炭治郎は新たな任務で、人を喰らう鬼と対峙する。その中で、鬼の過去を知ることになる。"
      },
      {
        number: 6,
        image: "/images/kimetsu-no-yaiba/volume-6.jpg",
        title: "お前の鼓動を聞け",
        releaseDate: "2017-04-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088811074",
        description: "炭治郎は新たな任務で、人を喰らう鬼と対峙する。その中で、鬼の過去を知ることになる。"
      },
      {
        number: 7,
        image: "/images/kimetsu-no-yaiba/volume-7.jpg",
        title: "猪の技",
        releaseDate: "2017-06-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088811570",
        description: "炭治郎は新たな任務で、人を喰らう鬼と対峙する。その中で、鬼の過去を知ることになる。"
      },
      {
        number: 11,
        image: "/images/kimetsu-no-yaiba/volume-11.jpg",
        title: "鬼滅の刃",
        releaseDate: "2018-02-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088814194",
      },
      {
        number: 14,
        image: "/images/kimetsu-no-yaiba/volume-14.jpg",
        title: "鬼滅の刃",
        releaseDate: "2018-08-03",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088815693",
      },
      {
        number: 17,
        image: "/images/kimetsu-no-yaiba/volume-17.jpg",
        title: "鬼滅の刃",
        releaseDate: "2019-02-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088816820",
      },
      {
        number: 23,
        image: "/images/kimetsu-no-yaiba/volume-23.jpg",
        title: "鬼滅の刃",
        releaseDate: "2020-05-13",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088821832",
      },
    ],
  },
  "shingeki-no-kyojin": {
    id: 3,
    title: "進撃の巨人",
    titleRomaji: "Shingeki no Kyojin",
    slug: "shingeki-no-kyojin",
    image: "/images/shingeki-no-kyojin/volume-1.jpg",
    description:
      "人類の生存圏が巨人によって脅かされる世界で、エレン・イェーガーと調査兵団の仲間たちが巨人の謎に挑む物語。",
    author: "諫山創",
    authorSlug: "isayama-hajime",
    publisher: "講談社",
    serialization: "別冊少年マガジン",
    years: "2009-2021",
    status: "完結",
    volumeCount: 34,
    rating: 4.8,
    genres: ["少年", "アクション", "ファンタジー", "ホラー"],
    volumes: [
      {
        number: 1,
        image: "/images/shingeki-no-kyojin/volume-1.jpg",
        title: "進撃の巨人",
        releaseDate: "2009-03-17",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063842760",
      },
      {
        number: 2,
        image: "/images/shingeki-no-kyojin/volume-2.jpg",
        title: "進撃の巨人",
        releaseDate: "2009-07-17",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063843384",
      },
      {
        number: 3,
        image: "/images/shingeki-no-kyojin/volume-3.jpg",
        title: "進撃の巨人",
        releaseDate: "2009-12-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063844100",
      },
      {
        number: 4,
        image: "/images/shingeki-no-kyojin/volume-4.jpg",
        title: "進撃の巨人",
        releaseDate: "2010-03-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063844623",
      },
      {
        number: 5,
        image: "/images/shingeki-no-kyojin/volume-5.jpg",
        title: "進撃の巨人",
        releaseDate: "2010-07-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063845131",
      },
      {
        number: 6,
        image: "/images/shingeki-no-kyojin/volume-6.jpg",
        title: "進撃の巨人",
        releaseDate: "2010-10-08",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063845646",
      },
      {
        number: 7,
        image: "/images/shingeki-no-kyojin/volume-7.jpg",
        title: "進撃の巨人",
        releaseDate: "2011-01-07",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063846162",
      },
      {
        number: 8,
        image: "/images/shingeki-no-kyojin/volume-8.jpg",
        title: "進撃の巨人",
        releaseDate: "2011-04-08",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063846685",
      },
      {
        number: 9,
        image: "/images/shingeki-no-kyojin/volume-9.jpg",
        title: "進撃の巨人",
        releaseDate: "2011-07-08",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063847207",
      },
      {
        number: 10,
        image: "/images/shingeki-no-kyojin/volume-10.jpg",
        title: "進撃の巨人",
        releaseDate: "2011-10-07",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/406384772X",
      },
      {
        number: 11,
        image: "/images/shingeki-no-kyojin/volume-11.jpg",
        title: "進撃の巨人",
        releaseDate: "2012-01-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/406384822X",
      },
      {
        number: 12,
        image: "/images/shingeki-no-kyojin/volume-12.jpg",
        title: "進撃の巨人",
        releaseDate: "2012-04-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063848726",
      },
      {
        number: 13,
        image: "/images/shingeki-no-kyojin/volume-13.jpg",
        title: "進撃の巨人",
        releaseDate: "2012-07-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063849226",
      },
      {
        number: 14,
        image: "/images/shingeki-no-kyojin/volume-14.jpg",
        title: "進撃の巨人",
        releaseDate: "2012-10-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063849722",
      },
      {
        number: 15,
        image: "/images/shingeki-no-kyojin/volume-15.jpg",
        title: "進撃の巨人",
        releaseDate: "2013-01-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063850224",
      },
      {
        number: 16,
        image: "/images/shingeki-no-kyojin/volume-16.jpg",
        title: "進撃の巨人",
        releaseDate: "2013-04-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063850720",
      },
      {
        number: 17,
        image: "/images/shingeki-no-kyojin/volume-17.jpg",
        title: "進撃の巨人",
        releaseDate: "2013-07-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063851220",
      },
      {
        number: 18,
        image: "/images/shingeki-no-kyojin/volume-18.jpg",
        title: "進撃の巨人",
        releaseDate: "2013-10-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063851727",
      },
      {
        number: 19,
        image: "/images/shingeki-no-kyojin/volume-19.jpg",
        title: "進撃の巨人",
        releaseDate: "2014-01-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063852227",
      },
      {
        number: 20,
        image: "/images/shingeki-no-kyojin/volume-20.jpg",
        title: "進撃の巨人",
        releaseDate: "2014-04-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063852723",
      },
      {
        number: 21,
        image: "/images/shingeki-no-kyojin/volume-21.jpg",
        title: "進撃の巨人",
        releaseDate: "2014-07-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063853223",
      },
      {
        number: 22,
        image: "/images/shingeki-no-kyojin/volume-22.jpg",
        title: "進撃の巨人",
        releaseDate: "2014-10-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063853723",
      },
      {
        number: 23,
        image: "/images/shingeki-no-kyojin/volume-23.jpg",
        title: "進撃の巨人",
        releaseDate: "2015-01-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063854223",
      },
      {
        number: 24,
        image: "/images/shingeki-no-kyojin/volume-24.jpg",
        title: "進撃の巨人",
        releaseDate: "2015-04-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063854723",
      },
      {
        number: 25,
        image: "/images/shingeki-no-kyojin/volume-25.jpg",
        title: "進撃の巨人",
        releaseDate: "2015-07-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063855223",
      },
      {
        number: 26,
        image: "/images/shingeki-no-kyojin/volume-26.jpg",
        title: "進撃の巨人",
        releaseDate: "2015-10-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063855723",
      },
      {
        number: 27,
        image: "/images/shingeki-no-kyojin/volume-27.jpg",
        title: "進撃の巨人",
        releaseDate: "2016-01-08",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063856223",
      },
      {
        number: 28,
        image: "/images/shingeki-no-kyojin/volume-28.jpg",
        title: "進撃の巨人",
        releaseDate: "2016-04-08",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063856723",
      },
      {
        number: 29,
        image: "/images/shingeki-no-kyojin/volume-29.jpg",
        title: "進撃の巨人",
        releaseDate: "2016-07-08",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063857223",
      },
      {
        number: 30,
        image: "/images/shingeki-no-kyojin/volume-30.jpg",
        title: "進撃の巨人",
        releaseDate: "2016-08-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063857908",
      },
      {
        number: 31,
        image: "/images/shingeki-no-kyojin/volume-31.jpg",
        title: "進撃の巨人",
        releaseDate: "2016-11-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063858416",
      },
      {
        number: 32,
        image: "/images/shingeki-no-kyojin/volume-32.jpg",
        title: "進撃の巨人",
        releaseDate: "2017-02-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063858924",
      },
      {
        number: 33,
        image: "/images/shingeki-no-kyojin/volume-33.jpg",
        title: "進撃の巨人",
        releaseDate: "2017-05-09",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4063859432",
      },
      {
        number: 34,
        image: "/images/shingeki-no-kyojin/volume-34.jpg",
        title: "進撃の巨人",
        releaseDate: "2021-06-09",
        pages: 200,
        amazonUrl: "https://www.amazon.co.jp/dp/4065234417",
      }
    ],
  },
  "one-piece": {
    id: 4,
    title: "ワンピース",
    titleRomaji: "One Piece",
    slug: "one-piece",
    image: "/images/one-piece/volume-97.jpg",
    description: "海賊王を夢見る少年モンキー・D・ルフィを主人公とする、「ひとつなぎの大秘宝（ワンピース）」を巡る海洋冒険ロマン。ゴムゴムの実を食べてゴム人間となったルフィは、仲間たちと共に大海原を冒険します。様々な島々で出会う人々との交流や戦いを通じて、友情と絆を深めていきます。世界政府や四皇など、強大な敵との戦いの中で、ルフィと仲間たちは成長を遂げ、それぞれの夢に向かって航海を続けます。壮大な世界観と個性的なキャラクターたちが織りなす、冒険と友情の物語です。",
    author: "尾田栄一郎",
    authorSlug: "oda-eiichiro",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "1997-",
    status: "連載中",
    volumeCount: 107,
    rating: 4.8,
    genres: ["少年", "アクション", "冒険", "コメディ"],
    volumes: [
      {
        number: 1,
        image: "/placeholder.svg?height=150&width=100",
        title: "ROMANCE DAWN",
        releaseDate: "1997-12-24",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088725093",
      },
      {
        number: 2,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1998-04-03",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088725387",
      },
      {
        number: 3,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1998-06-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088725603",
      },
      {
        number: 4,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1998-08-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088725891",
      },
      {
        number: 5,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1998-10-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088726170",
      },
      {
        number: 6,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1998-12-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088726421",
      },
      {
        number: 7,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1999-02-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088726715",
      },
      {
        number: 8,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1999-04-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088726995",
      },
      {
        number: 9,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1999-06-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088727290",
      },
      {
        number: 10,
        image: "/placeholder.svg?height=150&width=100",
        title: "ワンピース",
        releaseDate: "1999-08-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088727593",
      },
      {
        number: 97,
        image: "/images/one-piece/volume-97.jpg",
        title: "ONE PIECE",
        releaseDate: "2020-09-16",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088822137",
      }
    ],
  },
  "boku-no-hero-academia": {
    id: 5,
    title: "僕のヒーローアカデミア",
    slug: "boku-no-hero-academia",
    image: "/images/boku-no-hero-academia/volume-42.jpg",
    description: "個性（特殊能力）を持つ人間が当たり前の世界で、無個性の少年・緑谷出久がヒーローを目指す物語。",
    author: "堀越耕平",
    authorSlug: "horikoshi-kohei",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2014-",
    status: "連載中",
    volumeCount: 42,
    rating: 4.7,
    genres: ["少年", "アクション", "ヒーロー", "学園"],
    volumes: [
      {
        number: 42,
        image: "/images/boku-no-hero-academia/volume-42.jpg",
        title: "僕のヒーローアカデミア",
        releaseDate: "2024-08-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088836421",
      },
    ],
  },
  "naruto": {
    id: 6,
    title: "ナルト",
    slug: "naruto",
    image: "/images/naruto/volume-61.jpg",
    description:
      "忍者を目指す少年うずまきナルトの成長物語。里一番の忍者「火影」を目指し、仲間たちと共に数々の試練に立ち向かう。",
    author: "岸本斉史",
    authorSlug: "kishimoto-masashi",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "1999-2014",
    status: "完結",
    volumeCount: 72,
    rating: 4.8,
    genres: ["少年", "アクション", "忍者", "友情"],
    volumes: [
      {
        number: 1,
        image: "/images/naruto/volume-1.jpg",
        title: "うずまきナルト!!",
        releaseDate: "1999-03-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088730534",
      },
      {
        number: 61,
        image: "/images/naruto/volume-61.jpg",
        title: "忍界大戦、終結へ",
        releaseDate: "2012-09-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088704770",
        description: "第四次忍界大戦が激化する中、サスケとイタチの兄弟が大蛇丸のもとで再会。共に兜との戦いに挑む。",
        author: "岸本斉史",
        authorSlug: "kishimoto-masashi",
        publisher: "集英社",
        rating: 4.8,
      },
    ],
  },
  "dragon-ball": {
    id: 7,
    title: "ドラゴンボール",
    slug: "dragon-ball",
    image: "/images/dragon-ball/volume-1.jpg",
    description: "7つ集めると願いを叶えてくれるドラゴンボールを探す少年孫悟空の冒険物語。武道と友情、そして成長を描いた不朽の名作で、地球を守るため様々な強敵と戦いながら成長していきます。ピッコロ大魔王、フリーザ、セル、魔人ブウなど、次々と現れる強敵との戦いを通じて、悟空は超サイヤ人としての力を開花させていきます。仲間たちとの絆、家族愛、そして武道の精神を大切にしながら、宇宙規模の戦いに挑む壮大な物語です。",
    author: "鳥山明",
    authorSlug: "toriyama-akira",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "1984-1995",
    status: "完結",
    volumeCount: 42,
    rating: 4.9,
    genres: ["少年", "アクション", "冒険", "バトル"],
    volumes: [
      {
        number: 1,
        image: "/images/dragon-ball/volume-1.jpg",
        title: "孫悟空とブルマ",
        releaseDate: "1985-09-10",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088518314",
      },
    ],
  },
  "chainsaw-man": {
    id: 9,
    title: "チェンソーマン",
    slug: "chainsaw-man",
    image: "/images/chainsaw-man/volume-1.jpg",
    description: "悪魔と契約し、チェンソーの悪魔と融合した少年デンジが公安のデビルハンターとして活動します。独特な世界観とバイオレンスが話題のダークファンタジーで、人間と悪魔の境界を描きます。パワーやマキマなど、個性的なキャラクターたちとの出会い、そして様々な悪魔との戦いを通じて、デンジは人間としての成長を遂げていきます。欲望と正義、人間性と悪魔性の境界線を問う、深いテーマ性を持つ物語です。",
    author: "藤本タツキ",
    authorSlug: "fujimoto-tatsuki",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2018-2020",
    status: "完結",
    volumeCount: 11,
    rating: 4.7,
    genres: ["少年", "アクション", "ホラー", "ダークファンタジー"],
    volumes: [
      ...Array.from({ length: 11 }, (_, i) => ({
        number: i + 1,
        image: `/images/chainsaw-man/volume-${i + 1}.jpg`,
        title: "チェンソーマン",
        releaseDate: `2019-0${i + 3}-04`,
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088817788",
      })),
    ],
  },
  "blue-lock": {
    id: 8,
    title: "ブルーロック",
    slug: "blue-lock",
    image: "/images/blue-lock/volume-33.jpg",
    description: "日本をW杯優勝に導くストライカーを育成する青い監獄「ブルーロック」。300人の高校生FWの中から、たった一人の「世界一のエゴイスト」を選び出す極限のサバイバルで、サッカーの本質に迫ります。主人公の潔世一をはじめ、個性的な選手たちが独自のサッカー哲学を展開し、熾烈な競争を繰り広げます。チームプレイと個人の才能、勝利への執着とサッカーの本質など、様々な要素が絡み合いながら、選手たちの成長が描かれます。",
    author: "金城宗幸",
    authorSlug: "kaneshiro-muneyuki",
    publisher: "講談社",
    serialization: "週刊少年マガジン",
    years: "2018-",
    status: "連載中",
    volumeCount: 33,
    rating: 4.6,
    genres: ["少年", "スポーツ", "サッカー", "青春"],
    volumes: [
      {
        number: 33,
        image: "/images/blue-lock/volume-33.jpg",
        title: "ブルーロック",
        releaseDate: "2024-09-17",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4065337739",
      },
    ],
  },
  "yakusoku-no-neverland": {
    id: 14,
    title: "約束のネバーランド",
    slug: "yakusoku-no-neverland",
    image: "/images/yakusoku-no-neverland/volume-5.png",
    description: "孤児院で暮らす子供たちが、施設の恐ろしい真実を知り、脱出を図るサスペンス・ファンタジー。エマ、ノーマン、レイを中心に、子供たちの知恵と勇気を駆使した脱出劇が展開されます。人間と鬼の関係、家族愛、そして希望を失わないことの大切さを描く、深いテーマ性を持つ物語です。",
    author: "白井カイウ",
    authorSlug: "shirai-kaiu",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2016-2020",
    status: "完結",
    volumeCount: 20,
    rating: 4.7,
    genres: ["少年", "サスペンス", "ファンタジー", "ホラー"],
    volumes: [
      {
        number: 5,
        image: "/images/yakusoku-no-neverland/volume-5.png",
        title: "約束のネバーランド",
        releaseDate: "2018-05-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088812468",
      },
      ...Array.from({ length: 19 }, (_, i) => {
        const volNumber = i + 1 === 5 ? i + 2 : i + 1
        return {
          number: volNumber,
          image: "/placeholder.svg?height=150&width=100",
          title: `巻 ${volNumber}`,
          releaseDate: `201${6 + Math.floor(volNumber / 12)}-${(volNumber % 12) + 1}-01`,
          pages: 190 + (volNumber % 10),
        }
      }),
    ],
  },
  "haikyuu": {
    id: 17,
    title: "ハイキュー!!",
    slug: "haikyuu",
    image: "/images/haikyuu/volume-45.jpg",
    description: "身長の低さを武器に、バレーボールの世界で活躍する日向翔陽の成長を描くスポーツ漫画。烏野高校バレー部に入部した日向は、天才セッター影山と出会い、互いに切磋琢磨しながら全国大会を目指します。個性的な選手たちとの出会い、試合での熱い戦い、そしてチームとしての成長が描かれます。バレーボールの魅力と、スポーツを通じた人間関係の深さが伝わる作品です。",
    author: "古舘春一",
    authorSlug: "furudate-haruichi",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2012-2020",
    status: "完結",
    volumeCount: 45,
    rating: 4.8,
    genres: ["少年", "スポーツ", "バレーボール", "学園"],
    volumes: [
      {
        number: 45,
        image: "/images/haikyuu/volume-45.jpg",
        title: "ハイキュー!!",
        releaseDate: "2020-05-13",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088821688",
      },
    ],
  },
  "kuroko-no-basket": {
    id: 16,
    title: "黒子のバスケ",
    slug: "kuroko-no-basket",
    image: "/images/kuroko-no-basket/volume-10.png",
    description: "影の薄い少年・黒子テツヤが、バスケットボールの才能を持つ火神大我とタッグを組み、「キセキの世代」に挑むバスケットボール漫画。黒子の「見えないパス」と火神の圧倒的な身体能力が織りなす、独特のバスケットボールが展開されます。チームプレイの大切さ、個性の活かし方、そしてバスケットボールへの情熱が描かれます。",
    author: "藤巻忠俊",
    authorSlug: "fujimaki-tadatoshi",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2009-2014",
    status: "完結",
    volumeCount: 30,
    rating: 4.7,
    genres: ["少年", "スポーツ", "バスケットボール", "学園"],
    volumes: [
      {
        number: 10,
        image: "/images/kuroko-no-basket/volume-10.png",
        title: "黒子のバスケ",
        releaseDate: "2011-09-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088701909",
      },
    ],
  },
  "dai-dark": {
    id: 18,
    title: "ダイ大",
    slug: "dai-dark",
    image: "/images/dai-dark/volume-3.jpg",
    description: "宇宙を漂う少年・ザハ・サンコは、自分の骨を求める者たちに追われています。彼の骨を手に入れた者は望みを叶えられるという。相棒のシマダと共に、骨を狙う者たちから逃れながら、自分の出生の謎を追います。独特な世界観とキャラクターたちの個性が際立つSFホラーで、宇宙規模の冒険と謎解きが展開されます。人間と宇宙の関係性、生命の本質、そして存在の意味を問う、深いテーマ性を持つ物語です。",
    author: "林田球",
    authorSlug: "hayashida-q",
    publisher: "小学館",
    serialization: "月刊!スピリッツ",
    years: "2019-",
    status: "連載中",
    volumeCount: 8,
    rating: 4.7,
    genres: ["青年", "SFホラー", "ダークファンタジー", "アクション"],
    volumes: [
      {
        number: 3,
        image: "/images/dai-dark/volume-3.jpg",
        title: "ダイ大",
        releaseDate: "2020-04-10",
        pages: 184,
        amazonUrl: "https://www.amazon.co.jp/dp/4091295738",
      },
    ],
  },
  "historie": {
    id: 19,
    title: "ヒストリエ",
    slug: "historie",
    image: "/images/historie/volume-1.jpg",
    description: "古代マケドニアの大王アレクサンドロスに仕えた書記官エウメネスの波乱に満ちた生涯を描く歴史大作。緻密な時代考証と壮大なスケールで描かれる古代世界の物語です。奴隷から書記官となり、アレクサンドロスの側近として活躍するエウメネスの視点を通じて、古代マケドニアの政治、戦争、文化が描かれます。権力と人間性、戦争と平和、そして歴史の流れの中で生きる人々の姿が、深い洞察力で描かれています。",
    author: "岩明均",
    authorSlug: "iwaaki-hitoshi",
    publisher: "講談社",
    serialization: "月刊アフタヌーン",
    years: "2003-",
    status: "連載中",
    volumeCount: 12,
    rating: 4.8,
    genres: ["青年", "歴史", "ドラマ"],
    volumes: [
      {
        number: 1,
        image: "/images/historie/volume-1.jpg",
        title: "ヒストリエ",
        releaseDate: "2004-10-22",
        pages: 208,
        amazonUrl: "https://www.amazon.co.jp/dp/4063143341",
      },
      ...Array.from({ length: 11 }, (_, i) => ({
        number: i + 2,
        image: "/placeholder.svg?height=150&width=100",
        title: `巻 ${i + 2}`,
        releaseDate: `200${4 + Math.floor(i / 12)}-${(i % 12) + 1}-01`,
        pages: 200 + (i % 10),
      })),
    ],
  },
  "tokyo-revengers": {
    id: 10,
    title: "東京リベンジャーズ",
    slug: "tokyo-revengers",
    image: "/images/tokyo-revengers/volume-1.jpg",
    description: "ダメフリーターの花垣武道は、中学時代に付き合っていた橘日向が殺されたというニュースを知ります。翌日、駅のホームから転落した瞬間、12年前の中学時代にタイムリープし、未来を変えるために奔走します。東京卍會をはじめとする暴走族との関わり、仲間たちとの友情、そして日向を守るための戦いを通じて、武道は成長していきます。過去を変えることで未来を変えるという複雑な時間軸の中で、友情と正義を貫く物語です。",
    author: "和久井健",
    authorSlug: "wakui-ken",
    publisher: "講談社",
    serialization: "週刊少年マガジン",
    years: "2017-2022",
    status: "完結",
    volumeCount: 31,
    rating: 4.5,
    genres: ["少年", "アクション", "タイムリープ", "ヤンキー"],
    volumes: [
      {
        number: 1,
        image: "/images/tokyo-revengers/volume-1.jpg",
        title: "Rebirth",
        releaseDate: "2017-04-17",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4065091209",
      },
      ...Array.from({ length: 30 }, (_, i) => ({
        number: i + 2,
        image: "/placeholder.svg?height=150&width=100",
        title: `巻 ${i + 2}`,
        releaseDate: `20${Math.floor(17 + (i + 2) / 12)}-${((i + 2) % 12) + 1}-01`,
        pages: 190 + ((i + 2) % 10),
      })),
    ],
  },
  "world-trigger": {
    id: 15,
    title: "ワールドトリガー",
    slug: "world-trigger",
    image: "/images/world-trigger/volume-1.png",
    description: "異世界からの侵略者「近界民（ネイバー）」と戦う防衛組織「ボーダー」に所属する少年たちの戦いを描くSFアクション。主人公の三雲修をはじめ、個性的なトリガー使いたちが、近界民との戦いを通じて成長していきます。トリガーという特殊な武器を駆使した戦闘システム、緻密な戦術描写、そしてキャラクターたちの成長が魅力の作品です。",
    author: "葦原大介",
    authorSlug: "ashihara-daisuke",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2013-",
    status: "連載中",
    volumeCount: 25,
    rating: 4.6,
    genres: ["少年", "アクション", "SF", "チーム戦"],
    volumes: [
      {
        number: 1,
        image: "/images/world-trigger/volume-1.png",
        title: "空閑遊真",
        releaseDate: "2013-07-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088707087",
      },
      ...Array.from({ length: 24 }, (_, i) => ({
        number: i + 2,
        image: "/placeholder.svg?height=150&width=100",
        title: `巻 ${i + 2}`,
        releaseDate: `201${3 + Math.floor((i + 2) / 12)}-${((i + 2) % 12) + 1}-01`,
        pages: 190 + ((i + 2) % 10),
      })),
    ],
  },
  "bleach": {
    id: 12,
    title: "ブリーチ",
    slug: "bleach",
    image: "/images/bleach/volume-71.png",
    description: "死神の力を手に入れた高校生・黒崎一護が、虚（ホロウ）と呼ばれる悪霊と戦いながら成長していく物語。死神代行としての活動、尸魂界での戦い、そして仲間たちとの絆を通じて、一護は自分の力を開花させていきます。斬魄刀をはじめとする独特の戦闘システム、壮大な世界観、そしてキャラクターたちの成長が描かれます。",
    author: "久保帯人",
    authorSlug: "kubo-tite",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2001-2016",
    status: "完結",
    volumeCount: 74,
    rating: 4.6,
    genres: ["少年", "アクション", "ファンタジー", "バトル"],
    volumes: [
      {
        number: 71,
        image: "/images/bleach/volume-71.png",
        title: "The Dark Side of the Universe",
        releaseDate: "2016-04-04",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088808428",
      },
      ...Array.from({ length: 73 }, (_, i) => {
        const volNumber = i + 1 === 71 ? i + 2 : i + 1
        return {
          number: volNumber,
          image: "/placeholder.svg?height=150&width=100",
          title: `巻 ${volNumber}`,
          releaseDate: `200${1 + Math.floor(volNumber / 12)}-${(volNumber % 12) + 1}-01`,
          pages: 190 + (volNumber % 10),
        }
      }),
    ],
  },
  "gintama": {
    id: 13,
    title: "銀魂",
    slug: "gintama",
    image: "/images/gintama/volume-1.png",
    description: "江戸時代末期、天人（宇宙人）の襲来により侍の時代が終わった世界で、万事屋を営む坂田銀時の奮闘を描くSF時代劇コメディ。銀時と仲間たちが様々な依頼を請け負いながら、江戸の街で繰り広げる騒動と冒険。笑いと涙、そして熱い戦いが織りなす物語で、時には真剣な戦い、時にはバカバカしい日常を描きます。友情と正義、そして生きることの意味を問う、独特の世界観を持つ作品です。",
    author: "空知英秋",
    authorSlug: "sorachi-hideaki",
    publisher: "集英社",
    serialization: "週刊少年ジャンプ",
    years: "2003-2019",
    status: "完結",
    volumeCount: 77,
    rating: 4.7,
    genres: ["少年", "コメディ", "アクション", "SF"],
    volumes: [
      {
        number: 1,
        image: "/images/gintama/volume-1.png",
        title: "天然パーマに悪い奴はいない",
        releaseDate: "2004-04-02",
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088736214",
      },
      ...Array.from({ length: 76 }, (_, i) => ({
        number: i + 2,
        image: "/placeholder.svg?height=150&width=100",
        title: `巻 ${i + 2}`,
        releaseDate: `200${4 + Math.floor((i + 2) / 12)}-${((i + 2) % 12) + 1}-01`,
        pages: 190 + ((i + 2) % 10),
      })),
    ],
  },
}

// 巻のデータを取得する関数を更新
export function getMangaAndVolumeData(slug: string, volumeNumber: number) {
  const manga = getMangaData(slug)
  if (!manga) return null

  const volume = manga.volumes.filter((v): v is IMangaVolume => v !== null).find((v) => v.number === volumeNumber)
  if (!volume) return null

  // Return both the manga and the specific volume data
  return {
    manga: manga,
    volume: {
      ...volume,
      // Ensure description, author, publisher, rating are present for the volume if not explicitly defined
      description: volume.description || manga.description,
      author: volume.author || manga.author,
      authorSlug: volume.authorSlug || manga.authorSlug,
      publisher: volume.publisher || manga.publisher,
      rating: volume.rating || manga.rating,
    },
  }
}

// 他の関数は変更なし...
export function getMangaData(slug: string): Manga | null {
  let manga: Manga | null = null;

  if (mangaData[slug]) {
    manga = mangaData[slug];
    
    // ハンター×ハンターの場合、巻データを動的に生成
    if (slug === "hunter-x-hunter") {
      const baseVolumes = manga.volumes.slice(0, 3); // 最初の3巻は既存のデータを使用
      const generatedVolumes = Array.from({ length: 34 }, (_, i) => ({
        number: i + 4,
        image: `/images/hunter-x-hunter/volume-${i + 4}.jpg`,
        title: "ハンター×ハンター",
        releaseDate: `1999-${((i + 4) % 12) + 1}-01`,
        pages: 192,
        amazonUrl: "https://www.amazon.co.jp/dp/4088727533",
      }));
      manga.volumes = [...baseVolumes, ...generatedVolumes];
    }
  } else {
    const basicData = allMangaData.find((manga) => manga.slug === slug);
    if (!basicData) return null;

    manga = {
      id: basicData.id,
      title: basicData.title,
      titleRomaji: basicData.titleRomaji || basicData.title,
      slug: basicData.slug,
      image: basicData.image,
      description: basicData.description || `${basicData.title}の物語。`,
      author: basicData.author,
      authorSlug: basicData.authorSlug,
      publisher: basicData.publisher || "出版社",
      serialization: basicData.serialization || "連載誌",
      years: basicData.years || "連載期間",
      status: basicData.status || "連載状況",
      volumeCount: basicData.volumeCount,
      rating: basicData.rating || 4.5,
      genres: basicData.genres || ["ジャンル"],
      volumes: Array.from({ length: basicData.volumeCount }, (_, i) => ({
        number: i + 1,
        image: "/placeholder.svg?height=150&width=100",
        releaseDate: `発売日`,
        pages: 200,
        description: undefined,
      })),
    };
  }

  if (!manga) return null;

  // 巻数を基準に重複を排除し、並べ替える
  const uniqueVolumesMap = new Map<number, IMangaVolume>();
  manga.volumes.forEach(vol => {
    if (vol !== null) {
      // 既存の巻データがあればそれを優先する (例: プレースホルダーで上書きされないように)
      if (!uniqueVolumesMap.has(vol.number) || vol.image !== "/placeholder.svg?height=150&width=100") {
          uniqueVolumesMap.set(vol.number, vol);
      }
    }
  });
  manga.volumes = Array.from(uniqueVolumesMap.values()).sort((a, b) => a.number - b.number);

  // 作品のあらすじが提供されていない場合、最初の巻のあらすじを使用
  if (!manga.description && manga.volumes.length > 0 && manga.volumes[0]?.description) {
    manga.description = manga.volumes[0].description;
  }

  return manga;
}

// allMangaDataの更新
export const allMangaData: MangaSummary[] = [
  {
    id: 1,
    title: "ハンター×ハンター",
    slug: "hunter-x-hunter",
    image: "/images/hunter-x-hunter/volume-1.jpg",
    author: "冨樫義博",
    authorSlug: "togashi-yoshihiro",
    volumeCount: 37,
  },
  {
    id: 2,
    title: "進撃の巨人",
    slug: "shingeki-no-kyojin",
    image: "/images/shingeki-no-kyojin/volume-1.jpg",
    author: "諫山創",
    authorSlug: "isayama-hajime",
    volumeCount: 34,
  },
  {
    id: 3,
    title: "呪術廻戦",
    slug: "jujutsu-kaisen",
    image: "/images/jujutsu-kaisen/volume-4.jpg",
    author: "芥見下々",
    authorSlug: "akutami-gege",
    volumeCount: 28,
  },
  {
    id: 4,
    title: "鬼滅の刃",
    slug: "kimetsu-no-yaiba",
    image: "/images/kimetsu-no-yaiba/volume-7.jpg",
    author: "吾峠呼世晴",
    authorSlug: "gotouge-koyoharu",
    volumeCount: 23,
  },
  {
    id: 5,
    title: "ワンピース",
    slug: "one-piece",
    image: "/images/one-piece/volume-97.jpg",
    author: "尾田栄一郎",
    authorSlug: "oda-eiichiro",
    volumeCount: 107,
  },
  {
    id: 6,
    title: "僕のヒーローアカデミア",
    slug: "boku-no-hero-academia",
    image: "/images/boku-no-hero-academia/volume-42.jpg",
    author: "堀越耕平",
    authorSlug: "horikoshi-kohei",
    volumeCount: 42,
  },
  {
    id: 7,
    title: "ナルト",
    slug: "naruto",
    image: "/images/naruto/volume-61.jpg",
    author: "岸本斉史",
    authorSlug: "kishimoto-masashi",
    volumeCount: 72,
  },
  {
    id: 8,
    title: "ドラゴンボール",
    slug: "dragon-ball",
    image: "/images/dragon-ball/volume-1.jpg",
    author: "鳥山明",
    authorSlug: "toriyama-akira",
    volumeCount: 42,
  },
  {
    id: 9,
    title: "ブルーロック",
    slug: "blue-lock",
    image: "/images/blue-lock/volume-33.jpg",
    author: "金城宗幸",
    authorSlug: "kaneshiro-muneyuki",
    volumeCount: 33,
  },
  {
    id: 10,
    title: "チェンソーマン",
    slug: "chainsaw-man",
    image: "/images/chainsaw-man/volume-1.jpg",
    author: "藤本タツキ",
    authorSlug: "fujimoto-tatsuki",
    volumeCount: 11,
  },
  {
    id: 11,
    title: "東京リベンジャーズ",
    slug: "tokyo-revengers",
    image: "/images/tokyo-revengers/volume-1.jpg",
    author: "和久井健",
    authorSlug: "wakui-ken",
    volumeCount: 31,
  },
  {
    id: 12,
    title: "ブリーチ",
    slug: "bleach",
    image: "/images/bleach/volume-71.png",
    author: "久保帯人",
    authorSlug: "kubo-tite",
    volumeCount: 74,
  },
  {
    id: 13,
    title: "銀魂",
    slug: "gintama",
    image: "/images/gintama/volume-1.png",
    author: "空知英秋",
    authorSlug: "sorachi-hideaki",
    volumeCount: 77,
  },
  {
    id: 14,
    title: "約束のネバーランド",
    slug: "yakusoku-no-neverland",
    image: "/images/yakusoku-no-neverland/volume-5.png",
    author: "白井カイウ",
    authorSlug: "shirai-kaiu",
    volumeCount: 20,
  },
  {
    id: 15,
    title: "ワールドトリガー",
    slug: "world-trigger",
    image: "/images/world-trigger/volume-1.png",
    author: "葦原大介",
    authorSlug: "ashihara-daisuke",
    volumeCount: 25,
  },
  {
    id: 16,
    title: "黒子のバスケ",
    slug: "kuroko-no-basket",
    image: "/images/kuroko-no-basket/volume-10.png",
    author: "藤巻忠俊",
    authorSlug: "fujimaki-tadatoshi",
    volumeCount: 30,
  },
  {
    id: 17,
    title: "ハイキュー!!",
    slug: "haikyuu",
    image: "/images/haikyuu/volume-45.jpg",
    author: "古舘春一",
    authorSlug: "furudate-haruichi",
    volumeCount: 45,
  },
  {
    id: 18,
    title: "ダイ大",
    slug: "dai-dark",
    image: "/images/dai-dark/volume-3.jpg",
    author: "林田球",
    authorSlug: "hayashida-q",
    volumeCount: 8,
  },
  {
    id: 19,
    title: "ヒストリエ",
    slug: "historie",
    image: "/images/historie/volume-1.jpg",
    author: "岩明均",
    authorSlug: "iwaaki-hitoshi",
    volumeCount: 12,
  },
  {
    id: 20,
    title: "スラムダンク",
    slug: "slam-dunk",
    image: "/placeholder.svg?height=200&width=150",
    author: "井上雄彦",
    authorSlug: "inoue-takehiko",
    volumeCount: 31,
  },
  {
    id: 21,
    title: "テニスの王子様",
    slug: "prince-of-tennis",
    image: "/placeholder.svg?height=200&width=150",
    author: "許斐剛",
    authorSlug: "konomi-takeshi",
    volumeCount: 42,
  },
  {
    id: 22,
    title: "キャプテン翼",
    slug: "captain-tsubasa",
    image: "/placeholder.svg?height=200&width=150",
    author: "高橋陽一",
    authorSlug: "takahashi-yoichi",
    volumeCount: 37,
  },
  // 残りの78作品を追加
  ...Array.from({ length: 78 }, (_, i) => ({
    id: i + 23,
    title: `マンガタイトル${i + 23}`,
    slug: `manga-${i + 23}`,
    image: "/placeholder.svg?height=200&width=150",
    author: `作者${i + 23}`,
    authorSlug: `author-${i + 23}`,
    volumeCount: Math.floor(Math.random() * 50) + 1,
  })),
] 